@startuml

autonumber

title Webplex Avia Player - High Level Sequence Diagram

participant Player [
=Player
----
""dls""
]
database "User Platform" as UserPlatform #Ivory
participant Avia [
=Avia Instance
----
""avia-js""
]
participant PlaylistPlugin [
=Playlist Plugin
----
""avia-js""
]
participant WebPlugin [
=Web Plugin
----
""webplex-avia-plugins""
]
participant PlaylistService [
=Playlist Service
----
""webplex-avia-plugins""
]
database Topaz #Ivory

== Initialization ==

Player -[#red]> UserPlatform: Request Media token
UserPlatform -[#red]> Player: Media token
note left: Token TTL 5'
Player -> Avia: Create

Avia -> PlaylistPlugin: Load plugin
Avia -> WebPlugin: Load plugin

WebPlugin -> PlaylistService: Send Video Configs
note right
  This queue iterates over configs array
  & process item asynchronously.
end note

loop
  PlaylistService -[#red]> UserPlatform: Request new Media token if the one from step 2 expires
  UserPlatform -[#red]> PlaylistService: Media token
  PlaylistService -[#red]> Topaz: Request Mica
  Topaz -[#red]> PlaylistService: Mica response
  note left: Manifest URL TTL 5'
  PlaylistService -> PlaylistPlugin: Add Resource
  PlaylistService -> Avia: Register REQUEST hook to refresh Manifest URL
  note left
    This hook has a cost.
    It periodically repeats steps 7-10
  end note
end

PlaylistService -> WebPlugin: Ready
WebPlugin -> PlaylistPlugin: Start
PlaylistPlugin -> Avia: Start

== Playback ==

loop
  Avia -[#red]> Topaz: Request Manifest
  Topaz -[#red]> Avia: Manifest
  Avia -> WebPlugin: CONTENT_START
  ...Video playing...
  Avia -> Player: RESOURCE_END
end

@enduml